server:
  port: 8081
app:
  client:
    registration:
      client-id: client2
      client-secret: secret2
      token-uri: http://localhost:8080/oauth/token
      scopes: read,write
      client-name: client2
      jwk-set-uri: http://localhost:8080/.well-known/jwks.json
      authorization-uri: http://localhost:8080/oauth
      authorization-grant-type: authorization_code
      redirect-uri: http://localhost:8080/login