server:
  port: 9090
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth/token_key
        opaque:
          introspection-uri: http://localhost:8080/oauth/check_token
          introspection-client-id: resource-server
          introspection-client-secret: resource-server
key: classpath:key.pub


